name: Python Pipeline

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Update checkout action to latest
      - run: python hello.py

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Update checkout action to latest
      - uses: actions/upload-artifact@v4  # Fixed: Updated to v4
        with:
          name: hello
          path: .
